### ISSUE TITLE
[FEATURE] rDai dashboard

### ISSUE THREAD

**Issue by hellwolf** [rtoken-project/rtoken-analytics#1]
Acceptance criteria:

* User can view all the on/off-chain stats listed in https://github.com/decentral-ee/rtoken-contracts/issues/6

**Comment by hellwolf** [comment]
transferred from rtoken-contracts project, the description may be out dated.

**Comment by pi0neerpat** [comment]
@hellwolf is this satisfied by the explorer? Or is this something else?

**Comment by hellwolf** [comment]
Definitely!
